//------------------------------------------------------------------------
// Copyright(c) 2024 Steinberg Media Technologies.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"VST3 AU PlugIn.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"VST3 AU PlugIn VST3 (64Bit)"
#else
#define stringFileDescription	"VST3 AU PlugIn VST3"
#endif
#define stringCompanyName		"Steinberg Media Technologies\0"
#define stringLegalCopyright	"Copyright(c) 2024 Steinberg Media Technologies."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
